# Generated by Django 5.0.4 on 2024-05-15 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_citas_listuser_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='hora',
            field=models.TimeField(default=datetime.time(23, 24, 13, 243602)),
        ),
    ]
